### ISSUE TITLE
Prettier NPM script fails and takes me to index.js inside node_module\@schuchard

### ISSUE THREAD

**Issue by guillermoarellano** [schuchard/prettier-schematic#15] opened 2019-04-14 03:47 UTC
**Describe the bug**
When I run the prettier NPM script, the command never runs. Instead, it takes me to index.js file inside node_modules\@schuchard\prettier\src\prettier\. VS Code editor stops on line 19 of that file.

**To Reproduce**
1. Add schuchard\prettier schematic using ng add through NRWL's Angular Console
2. Configure prettier
3. Remove tslint.json conflicts
4. Run prettier NPM script from terminal inside project folder
5. ISSUE: Script command stops and VS Code editor takes me to index.js.

**Expected behavior**
Expected all of the files inside my project to get pretty. :)

**Screenshots**
Here's a screenshot of where my editor takes me soon after running the command.
![image](https://user-images.githubusercontent.com/19789981/56088003-e2585800-5e3c-11e9-9674-b2721e41ad55.png)

**Desktop (please complete the following information):**
Angular CLI: 7.3.5
Node: 10.13.0
OS: win32 x64
Angular: 7.2.9

**Additional context**
I removed @schuchard/prettier package from my dev dependencies in package.json file, while leaving the other packages that came from schematic intact, reinstalled prettier, and the NPM command worked. Strange...

**Comment by schuchard** [comment] 2019-04-17 02:50
thanks for reporting and the detailed steps to reproduce. Unfortunately 
1. I'm unable to reproduce. I've tested locally via `ng add` and through the Angular Console extension and the schematic installs and executes the `prettier` script successfully.
2. I don't have Windows machine to test on.

I'm not sure why the package.json `prettier` script would be executing the schematic though. It should be dealing with Prettier directly as the schematic has already run at this point. Is this the `prettier` script in package.json?
```json
"prettier": "prettier --write \"**/*.{js,json,css,md,ts,html,component.html}\"",
```

- did you have prettier already installed?
- is this a public repo? 
- can you provide any other information?

**Comment by schuchard** [comment] 2019-04-26 04:18
Closing until further information or steps to reproduce are available.

**Closed by schuchard** 2019-04-26 04:18 UTC

**Comment by guillermoarellano** [comment] 2019-04-26 16:27
Hi Kevin,

Yes, this was an existing repo where I had Prettier already installed. It is not a public repo yet. 

Let's close for now. I think it may have been a combination of having Prettier installed already with the schematic causing some potential conflicts. 

Thanks,
Guillermo

**Comment by schuchard** [comment] 2019-04-26 16:41
Sounds good. Thanks.

**Comment by petarblazevski** [comment] 2019-06-03 12:07
Greetings guys. I can confirm this issue is still happening. I am on Angular 7. The fix from @guillermoarellano did not work for me. I am on a Windows machine. In the following days, I will try it on a MacOS.
